# Generated by Django 4.2 on 2023-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_player_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='match',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
